use super::metadata::{Metadata, validate_identifier};
use anyhow::{Context, ensure};
use std::{
    fmt::Write as _,
    path::{Path, PathBuf},
};

fn license_file(name: &str) -> bool {
    let lower = name.to_ascii_lowercase();
    ["license", "licence", "copying", "notice"]
        .iter()
        .any(|prefix| {
            lower
                .strip_prefix(prefix)
                .is_some_and(|tail| tail.is_empty() || tail.starts_with(['.', '_', '-']))
        })
}

fn notices_in(directory: &Path, fallback: bool) -> anyhow::Result<Vec<PathBuf>> {
    if !directory.is_dir() {
        return Ok(Vec::new());
    }
    let mut paths = Vec::new();
    for entry in std::fs::read_dir(directory)? {
        let entry = entry?;
        let name = entry.file_name();
        if entry.file_type()?.is_file()
            && name.to_str().is_some_and(|name| {
                if fallback {
                    name.starts_with("LICENSE")
                } else {
                    license_file(name)
                }
            })
        {
            paths.push(entry.path());
        }
    }
    paths.sort();
    Ok(paths)
}

pub(super) fn generate(root: &Path, metadata: &Metadata) -> anyhow::Result<(String, String)> {
    let mut inventory = String::from(
        "# Resolved Crate License Inventory\n\nPatchPulse is licensed only under Apache-2.0. Dependencies retain their upstream licenses.\nThis inventory includes build, test, and Windows-only packages in the resolved graph.\nPrefer Apache-2.0 where offered; otherwise retain upstream MIT, BSD-3-Clause, Unicode-3.0, ISC and CDLA-Permissive-2.0 notices.\njiff is used under MIT. This does not relicense jiff or any other dependency.\n\nRegenerate with `cargo xtask dependency-policy --write` after dependency changes.\n\n| Crate | Version | Upstream license expression |\n| --- | --- | --- |\n",
    );
    let mut notices = String::from(
        "# Third-Party Crate Notices\n\nPatchPulse's own code is Apache-2.0. The following upstream license texts apply to the listed dependencies.\nThe inventory includes all resolved targets. Container base images and Rust toolchains retain their own notices.\nGenerated by cargo xtask dependency-policy; do not remove notices when distributing binaries.\n\n",
    );
    let mut packages: Vec<_> = metadata.packages.iter().collect();
    packages.sort_by(|a, b| (&a.name, &a.version).cmp(&(&b.name, &b.version)));
    let mut project_seen = false;
    for package in packages {
        validate_identifier(&package.name, false)?;
        validate_identifier(&package.version, true)?;
        ensure!(
            !matches!(package.name.as_str(), "chrono" | "time"),
            "Forbidden dependency: {}",
            package.name
        );
        if package.name == "patchpulse" {
            ensure!(
                package.license.as_deref() == Some("Apache-2.0"),
                "PatchPulse must be Apache-2.0 only"
            );
            project_seen = true;
            continue;
        }
        let license = package
            .license
            .as_deref()
            .filter(|value| !value.is_empty())
            .with_context(|| format!("Missing license metadata: {}", package.name))?;
        ensure!(
            !license.contains(['\n', '\r', '|']),
            "invalid license expression for {}",
            package.name
        );
        writeln!(
            inventory,
            "| {} | {} | {} |",
            package.name, package.version, license
        )?;
        let directory = package
            .manifest_path
            .parent()
            .context("manifest has no parent")?;
        let mut paths = notices_in(directory, false)?;
        if paths.is_empty() {
            paths = notices_in(
                &root
                    .join("licenses/upstream")
                    .join(format!("{}-{}", package.name, package.version)),
                true,
            )?;
        }
        ensure!(
            !paths.is_empty(),
            "No upstream license files found: {}",
            package.name
        );
        writeln!(
            notices,
            "## {} {}\n\nUpstream license expression: `{license}`.\n",
            package.name, package.version
        )?;
        for path in paths {
            let name = path
                .file_name()
                .and_then(|name| name.to_str())
                .context("non-UTF-8 license filename")?;
            let content = std::fs::read_to_string(&path)
                .with_context(|| format!("read license {}", path.display()))?;
            let content = content.replace("\r\n", "\n").replace('\r', "\n");
            writeln!(
                notices,
                "### {name}\n\n```text\n{}\n```\n",
                content.trim_end()
            )?;
        }
    }
    ensure!(project_seen, "metadata does not include PatchPulse");
    if notices.ends_with("\n\n") {
        notices.pop();
    }
    Ok((inventory, notices))
}

pub(super) fn run(root: &Path, metadata: &Metadata, write: bool) -> anyhow::Result<()> {
    let (inventory, notices) = generate(root, metadata)?;
    for (path, content) in [
        (root.join("docs/dependency-licenses.md"), inventory),
        (root.join("THIRD_PARTY_NOTICES.md"), notices),
    ] {
        if write {
            std::fs::create_dir_all(path.parent().context("output has no parent")?)?;
            std::fs::write(&path, content)?;
        } else {
            ensure!(
                std::fs::read_to_string(&path).ok().as_deref() == Some(&content),
                "Stale inventory: regenerate {} with cargo xtask dependency-policy --write",
                path.display()
            );
        }
    }
    println!("Dependency bans, Apache-2.0 project license, and upstream notices verified.");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tasks::{metadata::Package, test_support::Directory};
    fn project(root: &Path) -> Package {
        Package {
            name: "patchpulse".into(),
            version: "0.1.0".into(),
            license: Some("Apache-2.0".into()),
            manifest_path: root.join("Cargo.toml"),
            source: None,
        }
    }
    #[test]
    fn notice_names_match_boundaries_and_case() {
        for name in ["LICENSE", "licence.txt", "COPYING-MIT", "NOTICE_1"] {
            assert!(license_file(name));
        }
        for name in ["licensee.txt", "NOTICES", "readme.md"] {
            assert!(!license_file(name));
        }
    }
    #[test]
    fn banned_crates_and_project_license_are_enforced() {
        let dir = Directory::new();
        for name in ["chrono", "time"] {
            let mut banned = project(&dir.0);
            banned.name = name.into();
            assert!(
                generate(
                    &dir.0,
                    &Metadata {
                        packages: vec![project(&dir.0), banned]
                    }
                )
                .is_err()
            );
        }
        let mut invalid = project(&dir.0);
        invalid.license = Some("MIT OR Apache-2.0".into());
        assert!(
            generate(
                &dir.0,
                &Metadata {
                    packages: vec![invalid]
                }
            )
            .is_err()
        );
    }
    #[test]
    fn missing_archive_notices_use_exact_version_fallback() {
        let dir = Directory::new();
        let fallback = dir.0.join("licenses/upstream/example-1.0.0");
        std::fs::create_dir_all(&fallback).unwrap();
        std::fs::write(fallback.join("LICENSE"), "Original copyright\r\n").unwrap();
        let package = Package {
            name: "example".into(),
            version: "1.0.0".into(),
            license: Some("MIT".into()),
            manifest_path: dir.0.join("missing/Cargo.toml"),
            source: Some("registry+example".into()),
        };
        let metadata = Metadata {
            packages: vec![package, project(&dir.0)],
        };
        let generated = generate(&dir.0, &metadata).unwrap();
        assert!(generated.1.contains("Original copyright"));
        assert!(!generated.1.contains('\r'));
        run(&dir.0, &metadata, true).unwrap();
        run(&dir.0, &metadata, false).unwrap();
        std::fs::write(dir.0.join("docs/dependency-licenses.md"), "stale").unwrap();
        assert!(run(&dir.0, &metadata, false).is_err());
    }
}
