#!/usr/bin/env python3
"""Check dependency bans and generate inventory and upstream license notices."""

import argparse
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent


def generate(metadata):
    inventory = [
        "# Resolved Crate License Inventory", "",
        "PatchPulse is licensed only under Apache-2.0. Dependencies retain their upstream licenses.",
        "This inventory includes build, test, and Windows-only packages in the resolved graph.",
        "Prefer Apache-2.0 where offered; otherwise retain MIT and required BSD-3-Clause/Unicode-3.0 notices.",
        "jiff is used under MIT. This does not relicense jiff or any other dependency.", "",
        "Regenerate with `python3 scripts/dependency-policy.py --write` after dependency changes.", "",
        "| Crate | Version | Upstream license expression |",
        "| --- | --- | --- |",
    ]
    notices = [
        "# Third-Party Crate Notices", "",
        "PatchPulse's own code is Apache-2.0. The following upstream license texts apply to the listed dependencies.",
        "The inventory includes all resolved targets. Container base images and Rust toolchains retain their own notices.",
        "Generated by scripts/dependency-policy.py; do not remove notices when distributing binaries.", "",
    ]
    packages = sorted(metadata["packages"], key=lambda p: (p["name"], p["version"]))
    for package in packages:
        if package["name"] in {"chrono", "time"}:
            raise ValueError(f"Forbidden dependency: {package['name']}")
        if package["name"] == "patchpulse":
            if package["license"] != "Apache-2.0":
                raise ValueError("PatchPulse must be Apache-2.0 only")
            continue
        expression = package["license"]
        if not expression:
            raise ValueError(f"Missing license metadata: {package['name']}")
        inventory.append(f"| {package['name']} | {package['version']} | {expression} |")
        directory = Path(package["manifest_path"]).parent
        files = sorted(p for p in directory.iterdir() if p.is_file()
                       and re.match(r"^(licen[cs]e|copying|notice)([._-]|$)", p.name, re.I))
        if not files:
            fallback = ROOT / "licenses/upstream" / f"{package['name']}-{package['version']}"
            if fallback.exists():
                files = sorted(p for p in fallback.iterdir() if p.is_file() and p.name.startswith("LICENSE"))
        if not files:
            raise ValueError(f"No upstream license files found: {package['name']}")
        notices.extend([f"## {package['name']} {package['version']}", "",
                        f"Upstream license expression: `{expression}`.", ""])
        for path in files:
            notices.extend([f"### {path.name}", "", "```text", path.read_text(encoding="utf-8").rstrip(), "```", ""])
    return {ROOT / "docs/dependency-licenses.md": "\n".join(inventory) + "\n",
            ROOT / "THIRD_PARTY_NOTICES.md": "\n".join(notices)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--metadata", type=Path)
    args = parser.parse_args()
    if args.metadata:
        metadata = json.loads(args.metadata.read_text())
    else:
        metadata = json.loads(subprocess.check_output(
            ["cargo", "metadata", "--locked", "--all-features", "--format-version", "1"], cwd=ROOT))
    for path, content in generate(metadata).items():
        if args.write:
            path.write_text(content)
        elif not path.exists() or path.read_text() != content:
            raise ValueError(f"Stale inventory: regenerate {path.name} with --write")
    print("Dependency bans, Apache-2.0 project license, and upstream notices verified.")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)
